apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
  labels:
    app: react-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo
        image: saisamarth21/react-todo:latest   
        ports:
        - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: react-todo-service
spec:
  type: NodePort
  selector:
    app: react-todo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4173
    nodePort: 30080
